project:
  type: website
  output-dir: docs

website:
  site-url: "https://pierredenelle.github.io"
  title: "Pierre Denelle"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - pages/research_interests.qmd
      - pages/publications.qmd
      - pages/R_packages.qmd
    right: 
      - pages/about.qmd
      - text: "{{< iconify fa6-brands github size=2x >}}"
        href: "https://github.com/pierredenelle"
      - text: "{{< iconify academicons google-scholar size=2x >}}"
        href: "https://scholar.google.fr/citations?user=x66knTsAAAAJ&hl=en&oi=ao"
      - text: "{{< iconify simple-icons orcid size=2x >}}"  
        href: "https://orcid.org/0000-0002-4729-3774"
      - text: "{{< iconify simple-icons researchgate size=2x >}}"
        href: "https://www.researchgate.net/profile/Pierre-Denelle"
  page-footer:
    left: © Copyright 2024, Denelle Pierre
    right: This website is built with [{{< iconify simple-icons rstudioide size=2x >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}, and is hosted on [GitHub Pages](https://pages.github.com/){target=_blank}


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

