project:
  type: website
  output-dir: docs

website:
  title: "Pierre Denelle"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - publications.qmd
      - R_packages.qmd
      - about.qmd
    right: 
      - text: "{{< iconify fa6-brands github size=2x >}}"
        href: "https://github.com/pierredenelle"
      - text: "{{< iconify academicons google-scholar size=2x >}}"
        href: "https://scholar.google.fr/citations?user=x66knTsAAAAJ&hl=en&oi=ao"


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

