project:
  type: website
  output-dir: docs

website:
  title: "Pierre Denelle"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - publications.qmd
      - R_packages.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

